
low_level_keys = [
    'barkband_1', 'barkband_2','barkband_3','barkband_4', 'barkband_5',
    'barkband_6', 'barkband_7', 'barkband_8', 'barkband_9', 'barkband_10',
    'barkband_11', 'barkband_12','barkband_13','barkband_14', 'barkband_15',
    'barkband_16', 'barkband_17', 'barkband_18', 'barkband_19', 'barkband_20',
    'barkband_21', 'barkband_22','barkband_23','barkband_24', 'barkband_25',
    'barkband_26', 'barkband_27',
    'barkbands_kurtosis',
    'barkbands_skewness',
    'barkbands_spread',
    'hfc',
    'mfcc_1', 'mfcc_2', 'mfcc_3','mfcc_4','mfcc_5','mfcc_6',
    'mfcc_7','mfcc_8', 'mfcc_9', 'mfcc_10', 'mfcc_11', 'mfcc_12', 'mfcc_13',
    'pitch',
    'pitch_instantaneous_confidence',
    'pitch_salience',
    'silence_rate_20dB',
    'silence_rate_30dB',
    'silence_rate_60dB',
    'spectral_complexity',
    'spectral_crest',
    'spectral_decrease',
    'spectral_energy',
    'spectral_energyband_low',
    'spectral_energyband_middle_low',
    'spectral_energyband_middle_high',
    'spectral_energyband_high',
    'spectral_flatness_db',
    'spectral_flux',
    'spectral_rms',
    'spectral_rolloff',
    'spectral_strongpeak',
    'zerocrossingrate',
    'inharmonicity',
    'tristimulus_1', 'tristimulus_2', 'tristimulus_3',
    'oddtoevenharmonicenergyratio',
    'dissonance',
    'sccoeff_1',
    'sccoeff_2',
    'sccoeff_3',
    'sccoeff_4',
    'sccoeff_5',
    'sccoeff_6',
    'scvalley_1',
    'scvalley_2',
    'scvalley_3',
    'scvalley_4',
    'scvalley_5',
    'scvalley_6',
    'spectral_centroid',
    'spectral_kurtosis',
    'spectral_skewness',
    'spectral_spread'
]